# Generated by Django 5.2.8 on 2025-12-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_cadastro',
            new_name='UserCadastro',
        ),
    ]
