# Generated by Django 5.2.8 on 2026-02-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_user_cadastro_usercadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercadastro',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
