# Generated by Django 5.2.8 on 2026-04-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_usercadastro_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=120)),
                ('genero', models.CharField(max_length=120)),
                ('editora', models.CharField(max_length=120)),
                ('pagina_livro', models.PositiveIntegerField()),
                ('data_publicação', models.DateField()),
            ],
        ),
    ]
