# Generated by Django 5.2.8 on 2026-04-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
