# Generated by Django 5.2.8 on 2026-04-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_livro_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='livro_imagem',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
