# Generated by Django 5.2.8 on 2026-04-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_livro_livro_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='livro_imagem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
