# Generated by Django 5.2.8 on 2026-04-14 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_livro_livro_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinhaBiblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('imagem_capa', models.CharField(max_length=255)),
                ('id_livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.livro')),
            ],
        ),
    ]
