# Generated by Django 5.2.8 on 2026-04-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_minhabiblioteca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_livro', models.CharField(max_length=120)),
                ('autor', models.CharField(max_length=120)),
                ('paginas', models.PositiveIntegerField()),
                ('data', models.DateField()),
            ],
        ),
    ]
